name: Reusable workflow
on: 
  workflow_call:
    inputs:
      who-to-greet:
      description: 'Person to greet'
      required: true
      type: string
      default: World
    outputs:
      current-time:
        description: 'Time of greeting'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
  runs-on: ubuntu-latest
  outputs:
        current-time: ${{ steps.time.outputs.time }}
  steps:
    - name: Greet Someone
      run: echo "Hello ${{ inputs.who-to-greet }}"
    - name: Set output param
      id: time
      run: echo "time=$(date)" >> $GITHUB_OUTPUT
